#!/bin/bash

GREEN='\033[0;32m'
RESET='\033[0;37m'

MOUNT_HOST="shupet@flip1.engr.oregonstate.edu"
MOUNT_HOSTPATH="/nfs/stak/students/s/shupet"
MOUNT_MOUNTPOINT="/home/legion/mnt/flip"

echo -e "Mounting $GREEN$MOUNT_HOST$RESET \ndir:$GREEN$MOUNT_HOSTPATH$RESET \nat $GREEN$MOUNT_MOUNTPOINT$RESET"

sshfs $MOUNT_HOST:$MOUNT_HOSTPATH $MOUNT_MOUNTPOINT

echo "Mounting completed with exit code $?"
